### PR TITLE
Added two images that are hyperlinked. These images have a hover animation.

### PR DESCRIPTION
**Pull request by EdwinKimsal**
This is my first pull request, so please be harsh. Thanks for this wonderful opportunity to learn!

### CODE REVIEW

**Comment by sunami09** [comment]
Hey, @EdwinKimsal Would you like to join our organization?

**Comment by sunami09** [comment]
Your code is 2 commits behind, you might wanna git pull first. Apart from that, your code is correctly done. And add screenshots of your work or output in the pull request. Hoping to get your PR soon. 😀😀

**Comment by sunami09** [comment]
@EdwinKimsal Another thing If you want to work on an issue first you have to be assigned. So first put a comment on that issue page. That issue has already been issued to someone else. If she is unable to do so you will be assigned. Join our organization and you will get updates regarding the issues faster. I think you will be an asset to our organization.

**Comment by EdwinKimsal** [comment]
Sorry for that. Thanks for telling me about the pull request.

**Comment by EdwinKimsal** [comment]
Could you elaborate on the screenshots of the output? Just so I understand for the future.

**Comment by sunami09** [comment]
@EdwinKimsal You want to join us? 

And about the screenshot: take screenshots of the resulting webpage that you have created. For example screenshot of the Google Image Page that you have created.

**Comment by EdwinKimsal** [comment]
Thank you. I will pass on joining you, but thanks for the offer.

**Comment by sunami09** [comment]
Ok

**Pull request closed without merging**
